@startuml

interface BeanFactory {
getBean
}
interface ListableBeanFactory {
getBeanNamesForType
getBeansOfType
}
interface HierarchicalBeanFactory {
getParentBeanFactory
containsLocalBean
}

HierarchicalBeanFactory <|- BeanFactory

@enduml